Repository mikepenz/release-changelog-builder-action, pull requests merged in 2021-04, with the labels that each got.

#261 Bump @vercel/ncc from 0.28.0 to 0.28.2
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  dist/sourcemap-register.js
  package-lock.json
  package.json
Labels: dependencies

#262 dev -> main
  README.md
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  dist/sourcemap-register.js
  package-lock.json
  package.json
Labels: ignore

#279 dev -> main
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package-lock.json
  package.json
Labels: ignore

#291 Add base branches as configuration
  README.md
  __tests__/releaseNotes.test.ts
  configs_test/configuration_base_branches_develop.json
  configs_test/configuration_base_branches_main.json
  src/configuration.ts
  src/pullRequests.ts
  src/releaseNotes.ts
Labels: feature

#292 Support regex for base_branches config
  README.md
  dist/index.js
  dist/index.js.map
  package-lock.json
  src/releaseNotes.ts
Labels: feature

#293 dev -> main
  README.md
  __tests__/releaseNotes.test.ts
  configs_test/configuration_base_branches_develop.json
  configs_test/configuration_base_branches_main.json
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/configuration.ts
  src/pullRequests.ts
  src/releaseNotes.ts
Labels: ignore
