Repository mikepenz/release-changelog-builder-action, pull requests merged in 2022-01, with the labels that each got.

#632 Fix fetching PR iterator options, based on merge order
  src/pullRequests.ts
Labels: fix

#638 Dependency updates 2022.01.07
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/releaseNotesBuilder.ts
Labels: dependencies

#639 dev -> main
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/pullRequests.ts
  src/releaseNotesBuilder.ts
Labels: ignore

#654 Add ability to specify `on_property` as array
  README.md
  __tests__/transform.test.ts
  dist/index.js
  dist/index.js.map
  src/configuration.ts
  src/transform.ts
Labels: feature

#655 Update dependencies to latest stable version
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
Labels: dependencies

#656 dev -> main
  README.md
  __tests__/transform.test.ts
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/configuration.ts
  src/transform.ts
Labels: ignore
