Repository mikepenz/release-changelog-builder-action, pull requests merged in 2022-12, with the labels that each got.

#972 Use the default `github.token`
  action.yml
Labels: feature

#973 Fix `undefined` for `match` regex
  dist/index.js
  dist/index.js.map
  src/transform.ts
Labels: fix

#974 Update node dependencies
  package-lock.json
  package.json
Labels: dependencies

#961 Support to include review comments in the target PR template
  .prettierrc.json
  README.md
  __tests__/releaseNotes.test.ts
  __tests__/releaseNotesBuilder.test.ts
  __tests__/transform.test.ts
  action.yml
  dist/index.js
  dist/index.js.map
  src/configuration.ts
  src/main.ts
  src/pullRequests.ts
  src/releaseNotes.ts
  src/releaseNotesBuilder.ts
  src/tags.ts
  src/transform.ts
Labels: feature

#976 dev -> main
  .devcontainer/devcontainer.json
  .prettierrc.json
  README.md
  __tests__/releaseNotes.test.ts
  __tests__/releaseNotesBuilder.test.ts
  __tests__/transform.test.ts
  action.yml
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/configuration.ts
  src/main.ts
  src/pullRequests.ts
  src/releaseNotes.ts
  src/releaseNotesBuilder.ts
  src/tags.ts
  src/transform.ts
Labels: ignore
