Repository mikepenz/release-changelog-builder-action, pull requests merged in 2022-08, with the labels that each got.

#846 Introduce documentation on `experimental` custom placeholder feature
  README.md
  dist/index.js
  dist/index.js.map
  src/transform.ts
Labels: other

#847 Dependency updates - 2022.08.05
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
Labels: dependencies

#848 dev -> main
  README.md
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/transform.ts
Labels: ignore

#850 Add HTTPS proxy functionality
  README.md
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package-lock.json
  package.json
  src/releaseNotesBuilder.ts
Labels: feature

#857 Update dependencies 2022.08.10 | @actions/core
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package-lock.json
  package.json
Labels: dependencies

#858 dev -> main
  README.md
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  package-lock.json
  package.json
  src/releaseNotesBuilder.ts
  src/transform.ts
Labels: ignore

#870 dev -> main
  __tests__/transform.test.ts
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/tags.ts
  src/transform.ts
Labels: ignore

#871 Move `@types/semver` as dev only dependency
  package-lock.json
  package.json
Labels: dependencies

#880 Support `NO_PROXY` env config
  dist/index.js
  dist/index.js.map
  src/releaseNotesBuilder.ts
Labels: feature
