Repository mikepenz/release-changelog-builder-action, pull requests merged in 2023-01, with the labels that each got.

#994 Upgrade dev dependencies
  package-lock.json
  package.json
Labels: dependencies

#996 Add support for multi source configuration
  README.md
  __tests__/configuration.test.ts
  __tests__/releaseNotes.test.ts
  __tests__/releaseNotesBuilder.test.ts
  dist/index.js
  dist/index.js.map
  src/main.ts
  src/releaseNotes.ts
  src/releaseNotesBuilder.ts
  src/transform.ts
  src/utils.ts
Labels: feature

#997 Introduce `Rule` for categorisations
  README.md
  __tests__/transform.test.ts
  dist/index.js
  dist/index.js.map
  src/configuration.ts
  src/pullRequests.ts
  src/regexUtils.ts
  src/tags.ts
  src/transform.ts
  src/utils.ts
  src/wait.ts
Labels: feature

#998 dev -> main
  README.md
  __tests__/configuration.test.ts
  __tests__/releaseNotes.test.ts
  __tests__/releaseNotesBuilder.test.ts
  __tests__/transform.test.ts
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/configuration.ts
  src/main.ts
  src/pullRequests.ts
  src/regexUtils.ts
  src/releaseNotes.ts
  src/releaseNotesBuilder.ts
  src/tags.ts
  src/transform.ts
  src/utils.ts
  src/wait.ts
Labels: ignore

#1012 Small typo fix
  README.md
Labels: other
